In [14]:
# 4개 열 병합 -> 2만개 까지 cosine_similarity 가능, 전체 병합 -> 만개까지 가능
# 중복된 값 너무 많이나와서 제거함 -> 데이터가 50만개 에서 59000개 됨

In [150]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from pandas import Series, DataFrame

In [151]:
data = pd.read_excel("./printer_data (1).xlsx")

In [152]:
data.head()

상품명  productid        가격  \
0   ApeosPort 2560          1  20000000   
1   ApeosPort 3060          2  19500000   
2   ApeosPort 3560          3  18900000   
3  ApeosPort C2060          4  18711290   
4  ApeosPort C2560          5  18299940   

                                             keyword  productid.1  업종  근무자수  \
0  흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...            1   법    87   
1  흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...            2  기타    23   
2  흑백 디지털 복합기  잉크젯  컬러 출력  복사  스캔  인쇄 해상도: 4,800d...            3  교육    68   
3  컬러 디지털 복합기  인쇄  복사  스캔  컬러 속도: 23ppm  흑백 속도: 2...            4  행정    25   
4  컬러 디지털 복합기  인쇄  복사  스캔  팩스  컬러 속도: 23ppm  흑백 속...            5  행정    96   

   기본 급지용량  내구성          평균  
0      300    2  129.666667  
1     1290    3  438.666667  
2      530    2  200.000000  
3     1200    3  409.333333  
4     1350    2  482.666667

In [169]:
data=data.pivot_table(index=data['상품명'])

KeyError: '상품명'

In [167]:
data.head()

productid          가격          평균
상품명                                               
ApeosPort 2560         1.0  20000000.0  129.666667
ApeosPort 3060         2.0  19500000.0  438.666667
ApeosPort 3560         3.0  18900000.0  200.000000
ApeosPort C2060        4.0  18711290.0  409.333333
ApeosPort C2560        5.0  18299940.0  482.666667

In [176]:
data = data.drop(['가격'],axis=1)

In [177]:
data.head()

평균
상품명                        
ApeosPort 2560   129.666667
ApeosPort 3060   438.666667
ApeosPort 3560   200.000000
ApeosPort C2060  409.333333
ApeosPort C2560  482.666667

In [178]:
printer_sim = cosine_similarity(item_user_table,item_user_table)
printer_sim_df = pd.DataFrame(data=printer_sim,index=item_user_table.index,columns=item_user_table.index)
printer_sim_df

상품명                 ApeosPort 2560  ApeosPort 3060  ApeosPort 3560  \
상품명                                                                  
ApeosPort 2560            1.000000        0.967440        0.989048   
ApeosPort 3060            0.967440        1.000000        0.994192   
ApeosPort 3560            0.989048        0.994192        1.000000   
ApeosPort C2060           0.968194        0.999994        0.994515   
ApeosPort C2560           0.979353        0.998628        0.998462   
...                            ...             ...             ...   
코니카미놀타 bizhub 423         0.021967        0.019942        0.024108   
코니카미놀타 bizhub C200        0.021046        0.019641        0.023541   
코니카미놀타 bizhub C220        0.023830        0.020559        0.025259   
코니카미놀타 bizhub C360        0.033421        0.029815        0.034731   
코니카미놀타 bizhub C451        0.051796        0.048020        0.053152   

상품명                 ApeosPort C2060  ApeosPort C2560  ApeosPort C3060  \
상품명                                                                     
ApeosPort 2560             0.968194         0.979353         0.992592   
ApeosPort 3060             0.999994         0.998628         0.990969   
ApeosPort 3560             0.994515         0.998462         0.999639   
ApeosPort C2060            1.000000         0.998782         0.991376   
ApeosPort C2560            0.998782         1.000000         0.996630   
...                             ...              ...              ...   
코니카미놀타 bizhub 423          0.021642         0.022163         0.027840   
코니카미놀타 bizhub C200         0.021333         0.021733         0.027209   
코니카미놀타 bizhub C220         0.022273         0.023040         0.029120   
코니카미놀타 bizhub C360         0.031536         0.032415         0.038627   
코니카미놀타 bizhub C451         0.049749         0.050752         0.057067   

상품명                 ApeosPort-II C3000  ApeosPort-IV C2270  \
상품명                                                          
ApeosPort 2560                0.971466            0.991620   
ApeosPort 3060                0.999820            0.991613   
ApeosPort 3560                0.995828            0.999643   
ApeosPort C2060               0.999879            0.992025   
ApeosPort C2560               0.999334            0.996960   
...                                ...                 ...   
코니카미놀타 bizhub 423             0.029147            0.041633   
코니카미놀타 bizhub C200            0.028805            0.041018   
코니카미놀타 bizhub C220            0.029846            0.042882   
코니카미놀타 bizhub C360            0.039139            0.052375   
코니카미놀타 bizhub C451            0.057385            0.070796   

상품명                 ApeosPort-IV C2270CP  ApeosPort-IV C2270CPF  ...  \
상품명                                                              ...   
ApeosPort 2560                  0.980336               0.967711  ...   
ApeosPort 3060                  0.998280               0.999936  ...   
ApeosPort 3560                  0.998706               0.994306  ...   
ApeosPort C2060                 0.998466               0.999952  ...   
ApeosPort C2560                 0.999939               0.998654  ...   
...                                  ...                    ...  ...   
코니카미놀타 bizhub 423               0.031775               0.031097  ...   
코니카미놀타 bizhub C200              0.031332               0.030793  ...   
코니카미놀타 bizhub C220              0.032678               0.031719  ...   
코니카미놀타 bizhub C360              0.042059               0.040974  ...   
코니카미놀타 bizhub C451              0.060398               0.059175  ...   

상품명                 코니카미놀타 bizhub 211  코니카미놀타 bizhub 215  코니카미놀타 bizhub 283  \
상품명                                                                           
ApeosPort 2560               0.201636           0.060938           0.209236   
ApeosPort 3060               0.203377           0.060871           0.212747   
ApeosPort 3560               0.207350           0.064528           0.216037   


In [175]:
printer_sim_df["ApeosPort 2560"].sort_values(ascending=False)[1:10]

상품명
Apeosport-IV C3370 CPSF    0.997788
Apeosport-IV 3070CPS       0.997652
Apeosport-IV C3370         0.996455
Apeosport-IV C3370 CP      0.994546
Apeosport-II C4000         0.993830
ApeosPort C3060            0.992592
ApeosPort-IV C2270         0.991620
Apeosport-V C5575          0.991554
ApeosPort-IV C4470 CPSF    0.990770
Name: ApeosPort 2560, dtype: float64

In [159]:
keyword_c_sim = cosine_similarity(vector_keyword, vector_keyword).argsort()[:, ::-1]

In [160]:
keyword_c_sim.shape

(5901, 5901)

In [161]:
def get_recommend_list(df, title, top=30):
    #특정 상품의 정보를가져온다.
    target_index = df[df['상품명'] == title].index.values
    
    #비슷한 코사인 유사도를 가진 정보를 뽑아 1차원배열로 저장한다.
    sim_index = keyword_c_sim[target_index, :top].reshape(-1) 
    #자기 자신은 제외한다.
    sim_index = sim_index[sim_index != target_index]
    
    #dataframe으로 만들고 가장 비슷한 10개의 항목을 return 한다.
    result = df.iloc[sim_index][:10]
    return result

In [52]:
data.shape

(5901, 6)

In [162]:
get_recommend_list(data, title='ApeosPort 2560')

상품명  productid       가격  \
660                   Canon iR2525        661  2499950   
130            Brother MFC-L6900DW        131  3350000   
585                  Canon iR2206F        586  2593940   
3655        Kyocera TASKalfa 4012i       3656        0   
618                   Canon IR2425        619  2500000   
3614         Kyocera FS-1035MFP/DP       3615        0   
2197  Epson WorkForce Pro WF-C8690       2198   358800   
515                 Canon IR C3125        516  2689000   
372          Canon IR ADV DX C3725        373  2759100   
353          Canon IR ADV DX C3725        354  2759100   

                                                keyword  업종          평균  
660   의류 흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  ...  의류  138.333333  
130   은행 흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  ...  은행  176.333333  
585   행정 흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  ...  행정   87.666667  
3655  병원 흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  ...  병원  479.666667  
618   교육 흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  ...  교육  492.000000  
3614  기타 흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  ...  기타  259.000000  
2197  법 컬러 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인...   법  461.000000  
515   법 컬러 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인...   법  269.000000  
372   법 컬러 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인...   법  183.666667  
353   법 컬러 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인...   법  124.000000

In [54]:
vector_keyword = vector.fit_transform(data['f'])

In [55]:
# keyword를 코사인 유사도로 유사도 측정
keyword_c_sim = cosine_similarity(vector_keyword, vector_keyword).argsort()[:, ::-1]

In [59]:
keyword_c_sim.shape
print(keyword_c_sim)

[[   0 2197  372 ... 5576 5525   62]
 [   1 3656 3697 ... 5525 5576   62]
 [   2 3698 1746 ... 5576 5525   62]
 ...
 [5898 4242 5793 ... 3156 2977   62]
 [4215 5899 5667 ... 3753 5170   62]
 [5900 4917 4539 ...  808  556   62]]


In [57]:
#상품 추천
def get_recommend_list(df, title, top=30):
    #특정 상품의 정보를가져온다.
    target_index = df[df['상품명'] == title].index.values
    
    #비슷한 코사인 유사도를 가진 정보를 뽑아 1차원배열로 저장한다.
    sim_index = keyword_c_sim[target_index, :top].reshape(-1)
    
    #자기 자신은 제외한다.
    sim_index = sim_index[sim_index != target_index]
    
    #dataframe으로 만들고 가장 비슷한 10개의 항목을 return 한다.
    result = df.iloc[sim_index][:10]
    return result

In [58]:
get_recommend_list(data, title='ApeosPort 2560')

상품명  productid       가격  productid.1  \
2197  Epson WorkForce Pro WF-C8690       2198   358800         2198   
372          Canon IR ADV DX C3725        373  2759100          373   
353          Canon IR ADV DX C3725        354  2759100          354   
515                 Canon IR C3125        516  2689000          516   
585                  Canon iR2206F        586  2593940          586   
618                   Canon IR2425        619  2500000          619   
130            Brother MFC-L6900DW        131  3350000          131   
3614         Kyocera FS-1035MFP/DP       3615        0         3615   
660                   Canon iR2525        661  2499950          661   
3655        Kyocera TASKalfa 4012i       3656        0         3656   

              평균                                                  f  
2197  461.000000  컬러 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...  
372   183.666667  컬러 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...  
353   124.000000  컬러 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...  
515   269.000000  컬러 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...  
585    87.666667  흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...  
618   492.000000  흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...  
130   176.333333  흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...  
3614  259.000000  흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...  
660   138.333333  흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...  
3655  479.666667  흑백 디지털 복합기  잉크젯  포토프린터  컬러 출력  복사  스캔  팩스  인쇄 ...